version: '2.1'
services:

    webapp:
        image: node:9.9
        networks:
            - stage
        ports:
            - ${PROXY_PORT:-8080}:8080
        environment:
            NODE_ENV: production
            LOG_LEVEL: ${LOG_LEVEL-info}
            SSR_PORT: 8080
            SSR_ENABLED: ${SSR_ENABLED-no}
            SSR_BUILD: ${SSR_BUILD:-/usr/src/app/build}
            SSR_ROOT: ${SSR_ROOT:-/usr/src/app/src}
            SSR_TIMEOUT: ${SSR_TIMEOUT:-5000}
            SSR_DISABLE_JS: ${SSR_DISABLE_JS:-no}
            SSR_USE_WEBPACK_JS: ${SSR_USE_WEBPACK_JS:-no}
            SSR_BLACKLIST: ${SSR_BLACKLIST:-}
        volumes:
            - ./services/webapp:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start:prod" ]
        # restart: always

networks:
    stage:
